version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lastuser
      POSTGRES_USER: lastuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  backend:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://lastuser:secret@postgres/lastuser
      KAFKA_BROKER: kafka:9092
    depends_on:
      - postgres
      - kafka
    ports:
      - "8000:8000"

  worker:
    build: ./worker
    command: python main.py
    volumes:
      - ./worker:/worker
    environment:
      DATABASE_URL: postgresql+asyncpg://lastuser:secret@postgres/lastuser
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
      - postgres
